app/controllers/GetInterestsController.scala, project/AppDependencies.scala, project/plugins.sbt, test/controllers/GetInterestsControllerSpec.scala, test/testUtils/TestSuite.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-677
=> upgraded dependencies

conf/application.conf
Turning off metrics locally in our repos but enabling in app-config-base
[SASS-939](https://jira.tools.tax.service.gov.uk/browse/SASS-899)
=> [SASS-939] - Turning metrics off locally

app/connectors/httpParsers/CreateOrAmendInterestHttpParser.scala, it/connectors/CreateOrAmendInterestConnectorISpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/controllers/CreateOrAmendInterestControllerSpec.scala
Aligned API-1390 (Create/update Income source) to version 2.1.0
[SASS-1162](https://jira.tools.tax.service.gov.uk/browse/SASS-1162)
=> SASS-1162 : update API-1390 to align with version 2.1.0

app/config/AppConfig.scala, it/connectors/CreateIncomeSourcesConnectorISpec.scala, it/connectors/CreateOrAmendInterestConnectorISpec.scala, it/connectors/GetIncomeSourceDetailsConnectorSpec.scala, it/connectors/GetIncomeSourceListConnectorSpec.scala, project/AppDependencies.scala, test/connectors/httpParsers/DESParserSpec.scala, test/testUtils/MockAppConfig.scala, test/testUtils/TestSuite.scala
Removal of injection from unit tests
[SASS-739](https://jira.tools.tax.service.gov.uk/browse/SASS-739)
=> SASS-1611 : Removed Injection from Unit Tests

project/AppDependencies.scala
[SASS-2960](https://jira.tools.tax.service.gov.uk/browse/SASS-2960)
=> SASS-2960 - Update bootstrap-BE/FE-play-28 dependencies.

app/connectors/DeleteSavingsIncomeDataConnector.scala, app/connectors/httpParsers/DeleteSavingsIncomeDataParser.scala, app/controllers/DeleteSavingsIncomeDataController.scala, app/services/DeleteSavingsIncomeDataService.scala, conf/app.routes, it/connectors/DeleteSavingsIncomeDataConnectorISpec.scala, it/helpers/WiremockStubHelpers.scala, test/controllers/DeleteSavingsIncomeDataControllerSpec.scala, test/services/DeleteSavingsIncomeDataSpec.scala
[SASS-3567](https://jira.tools.tax.service.gov.uk/browse/SASS-3567)
- [ x]  Have you run the tests?
=> SASS-3362 Delete Savings Income Submission added

app/controllers/predicates/AuthorisedAction.scala, conf/application.conf, test/controllers/predicates/AuthorisedActionSpec.scala, test/testUtils/TestSuite.scala
Increasing the minimum Confidence Level value to 250 rather than 200
SASS-3946 https://jira.tools.tax.service.gov.uk/browse/SASS-3946
=> SASS-3946 Increase the 'Confidence Level' to 250 from 200

app/controllers/predicates/AuthorisedAction.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
[SASS-4363](https://jira.tools.tax.service.gov.uk/browse/SASS-4363)
=> SASS-4363 Update dependencies for income_tax_interest

app/connectors/httpParsers/CreateOrAmendSavingsHttpParser.scala, it/connectors/CreateOrAmendSavingsConnectorISpec.scala
[SASS-3739](https://jira.tools.tax.service.gov.uk/browse/SASS-3621)
=> update interest savings submit

conf/application.conf, project/AppDependencies.scala, project/plugins.sbt
SASS-4862 https://jira.tools.tax.service.gov.uk/browse/SASS-4862
=> SASS-4862 Update dependencies

app/config/AppConfig.scala, app/connectors/CreateOrAmendSavingsConnector.scala, app/connectors/DeleteSavingsIncomeDataConnector.scala, app/connectors/DesConnector.scala, app/connectors/GetSavingsIncomeDataConnector.scala, conf/application.conf, test/support/stubs/AppConfigStub.scala, test/testUtils/MockAppConfig.scala
[SASS-CHANGE-ME](ADD URL HERE)
=> update des api

app/connectors/CreateOrAmendSavingsConnector.scala, app/services/CreateOrAmendInterestService.scala, app/services/GetInterestsService.scala, app/utils/TaxYearUtils.scala, it/connectors/CreateOrAmendAnnualIncomeSourcePeriodConnectorISpec.scala, it/connectors/GetAnnualIncomeSourcePeriodConnectorISpec.scala, test/services/CreateOrAmendInterestServiceSpec.scala, test/services/GetInterestsServiceSpec.scala
[SASS-CHANGE-ME](ADD URL HERE)
=> SASS-5051 Implement TYS APIs to handle future tax years

app/connectors/GetSavingsIncomeDataTysConnector.scala, app/services/GetSavingsIncomeDataService.scala, build.sbt, conf/application.conf, conf/prod.routes, it/connectors/GetSavingsIncomeDataTysConnectorISpec.scala, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/services/GetSavingsIncomeDataServiceSpec.scala
=> SASS-7032: Add TYS API 1904

app/connectors/CreateOrAmendSavingsTysConnector.scala, it/connectors/CreateOrAmendSavingsTysConnectorISpec.scala
Fixed url for connector to send payload to correct TYS API (1903)
Work relates to main ticket SASS-7116
=> SASS-7118_B: Amended url in CreateOrAmendSavingsTysConnector

app/connectors/DeleteSavingsIncomeDataTysConnector.scala, app/connectors/httpParsers/DeleteSavingsIncomeDataParser.scala, app/services/DeleteSavingsIncomeDataService.scala, conf/application.conf, it/connectors/CreateOrAmendSavingsTysConnectorISpec.scala, it/connectors/DeleteSavingsIncomeDataTysConnectorISpec.scala, test/services/DeleteSavingsIncomeDataServiceSpec.scala
Added code and tests for TYS API 1905 (Delete Savings Income)
The work undertaken on this branch relates to main ticket SASS-7120.
=> SASS-7121: Added TYS API 1905 

app/controllers/CreateOrAmendSavingsController.scala, app/models/CreateOrAmendSavingsModel.scala, app/models/SavingsIncomeDataModel.scala, it/connectors/CreateOrAmendSavingsConnectorISpec.scala, it/connectors/CreateOrAmendSavingsTysConnectorISpec.scala, it/connectors/GetSavingsIncomeDataConnectorISpec.scala, it/connectors/GetSavingsIncomeDataTysConnectorISpec.scala, test/controllers/CreateOrAmendSavingsControllerSpec.scala, test/controllers/GetSavingsIncomeDataControllerSpec.scala, test/services/CreateOrAmendSavingsServiceSpec.scala, test/services/GetSavingsIncomeDataServiceSpec.scala
=> Sass 7308: Update model to match spec

app/config/AppConfig.scala, app/controllers/CommonTaskListController.scala, app/models/AllInterest.scala, app/models/tasklist/SectionTitle.scala, app/models/tasklist/TaskListSection.scala, app/models/tasklist/TaskListSectionItem.scala, app/models/tasklist/TaskStatus.scala, app/models/tasklist/TaskTitle.scala, app/services/CommonTaskListService.scala, build.sbt, conf/app.routes, conf/application.conf, conf/logback.xml, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/controllers/CommonTaskListControllerSpec.scala, test/models/taskList/SectionTitleSpec.scala, test/models/taskList/TaskStatusSpec.scala, test/models/taskList/TaskTitleSpec.scala, test/services/CommonTaskListServiceSpec.scala, test/support/stubs/AppConfigStub.scala, test/testUtils/MockAppConfig.scala, test/testUtils/TestSuite.scala
[SASS-CHANGE-ME](ADD URL HERE)
=> SASS-9293 | Added TaskList Endpoint for Interest with working unit tests

app/models/tasklist/TaskTitle.scala, app/services/CommonTaskListService.scala, test/models/taskList/TaskTitleSpec.scala, test/services/CommonTaskListServiceSpec.scala
PR raised to correct the naming of Task Title object so incoming Json objects match for validation purposes
Amendment was completed against main ticket - SASS-8104
=> SASS-9593: Renamed Task Title object for json validation purposes

app/common/EnrolmentCommon.scala, app/config/AppConfig.scala, app/controllers/predicates/AuthorisedAction.scala, app/utils/HMRCHeaderNames.scala, conf/application.conf, project/plugins.sbt, test/controllers/CreateOrAmendSavingsControllerSpec.scala, test/controllers/JourneyAnswersControllerSpec.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/support/stubs/AppConfigStub.scala, test/testUtils/MockAppConfig.scala, test/testUtils/TestSuite.scala, test/testUtils/UnitTest.scala
[SASS-CHANGE-ME](ADD URL HERE)
=> Sass 10733 - EMA changes for interest

app/controllers/predicates/AuthorisedAction.scala, check.sh, test/controllers/predicates/AuthorisedActionSpec.scala
=> [SASS-10777] Handle auth exceptions and update logging levels

app/models/IncomeSourceType.scala, app/models/InterestSubmissionModel.scala, app/services/CreateOrAmendInterestService.scala, it/test/connectors/CreateIncomeSourcesConnectorISpec.scala, test/models/IncomeSourceTypeSpec.scala, test/models/InterestSubmissionModelSpec.scala, test/services/CreateOrAmendInterestServiceSpec.scala
=> [SASS-11927] Correct the incomeSourceType in model
